// GENERATED by services/api/scripts/firebase-autoconfig.js — do not edit by hand.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not a target for the customer app.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError('Only Android is configured. Run flutterfire configure for others.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBBpoMinhARN-QJCkFlrB9WFmWa0ItuAU',
    appId: '1:828032047988:android:40f33778f3d2e6477faa21',
    messagingSenderId: '828032047988',
    projectId: 'kawkaw08',
    storageBucket: 'kawkaw08.firebasestorage.app',
  );
}
